"""`dataguard-insider`: the UC2 Insider Risk command line.

dataguard-insider data build                      regenerate the synthetic data (byte-identical)
dataguard-insider ml eval                         holdout anomaly-detector evaluation (no model calls)
dataguard-insider investigate I13 [--arch full|lean|single] [--mode offline|replay|live] [--json]
dataguard-insider eval [--mode offline|replay] [--arch ...] [--ids I13,I24]
dataguard-insider record --ids ... [--arch ...] [--backend ...]   LIVE: record agent turns for replay
dataguard-insider agent schemas <role>            print a role's tool definitions (Foundry setup)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "docs" / "uc2" / "results"


def _ml_md(r: dict) -> str:
    sep, b, mb = r["separation"], r["bands"], r["matched_budget"]
    k = r["provenance"]["review_budget_per_day"]
    lines = [
        "# UC2 anomaly-detector evaluation (generated)", "",
        "Generated by `dataguard-insider ml eval`. OFFLINE and deterministic: no model calls.", "",
        f"> {r['statement']}", "",
        f"* Training: {r['provenance']['train_user_days']} historical user-days (normal behaviour only). "
        f"Holdout: {r['provenance']['holdout_user_days']} user-days, of which {r['provenance']['positives']} "
        f"are injected anomalies and {r['provenance']['hard_legitimate']} hard-legitimate patterns.",
        f"* Model fingerprint `{r['provenance']['model_fingerprint']}`; bands from training-score percentiles: "
        f"ELEVATED ≥ {r['thresholds']['elevated']}, HIGH_ANOMALY ≥ {r['thresholds']['high']}.", "",
        "## Separation", "",
        "| | Isolation Forest | Statistical baseline |", "|---|---|---|",
        f"| ROC-AUC (evaluation labels) | {sep['roc_auc']['isolation_forest']} | {sep['roc_auc']['statistical_baseline']} |",
    ]  # fmt: skip
    for g in ("normal", "legitimate", "anomaly"):
        a, s = sep["isolation_forest_scores"][g], sep["statistical_scores"][g]
        lines.append(f"| median score, {g} (n={a['n']}) | {a['median']} | {s['median']} |")
    lines += ["", "## Matched analyst review budget (top-k per day)", "",
              "| Budget | IF precision | IF recall | Baseline precision | Baseline recall |", "|---|---|---|---|---|"]  # fmt: skip
    for kk, v in mb.items():
        i, s = v["isolation_forest"], v["statistical_baseline"]
        lines.append(
            f"| {kk}/day | {i['precision']} | {i['recall']} | {s['precision']} | {s['recall']} |"
        )
    lines += [
        "",
        "## Alert bands",
        "",
        "| Rule | Alerts | Alert rate | Precision | Recall |",
        "|---|---|---|---|---|",
    ]
    for name, v in (("IF ≥ ELEVATED", b["if_elevated_or_higher"]), ("IF HIGH_ANOMALY", b["if_high"]),
                    ("Statistical rule", b["statistical_rule"])):  # fmt: skip
        lines.append(
            f"| {name} | {v['alerts']} | {v['alert_rate']} | {v['precision']} | {v['recall']} |"
        )
    lines += ["", f"## Per scenario (budget {k}/day)", "",
              "| Scenario | Kind | User-days | IF bands | IF caught | Baseline caught |", "|---|---|---|---|---|---|"]  # fmt: skip
    for s in r["per_scenario"]:
        lines.append(f"| {s['scenario']} | {s['kind']} | {s['user_days']} | {s['if_bands']} | "
                     f"{s['if_caught_at_budget']} | {s['stat_caught_at_budget']} |")  # fmt: skip
    lines += ["", "## Alert rate on normal user-days, by role family (fairness check; not tuned)", "",
              "| Role family | Normal user-days | IF alert rate | Baseline flag rate |", "|---|---|---|---|"]  # fmt: skip
    for fam, v in r["role_family_alert_rates"].items():
        lines.append(
            f"| {fam} | {v['normal_user_days']} | {v['if_alert_rate']} | {v['stat_flag_rate']} |"
        )
    f = r["flagship"]
    lines += ["", "## Flagship (u-2043, 2026-08-25)", "",
              f"Score **{f['anomaly_score']}**, band **{f['anomaly_band']}**. Contributing signals (reset-to-baseline):", "",
              "| Feature | Observed | Baseline median | Ratio | Score drop if reset |", "|---|---|---|---|---|"]  # fmt: skip
    for c in f["contributing_signals"]:
        lines.append(f"| {c['feature']} | {c['observed']} | {c['baseline_median']} | "
                     f"{c['ratio_to_baseline'] or 'new (baseline 0)'} | {c['score_drop_if_reset']} |")  # fmt: skip
    return "\n".join(lines) + "\n"


def _agents_md(r: dict) -> str:
    lines = ["# UC2 investigation evaluation (generated)", "",
             f"Generated by `dataguard-insider eval`. Verification: **{r['verification']}**; backend `{r['backend']}`; "
             f"{r['cases']} golden cases. Monetary cost: NOT_ESTIMATED (no dated pricing configured).", ""]  # fmt: skip
    archs = list(r["architectures"])
    keys = list(r["architectures"][archs[0]]["summary"])
    lines += ["| Metric | " + " | ".join(archs) + " |", "|---|" + "---|" * len(archs)]
    for k in keys:
        lines.append(
            f"| {k} | " + " | ".join(str(r["architectures"][a]["summary"][k]) for a in archs) + " |"
        )
    lines += ["", "## Misses", ""]
    for a in archs:
        miss = [x for x in r["architectures"][a]["rows"] if not x["ok"]]
        lines.append(
            f"* **{a}**: "
            + (
                ", ".join(f"{x['id']} expected {x['expected']} got {x['outcome']}" for x in miss)
                or "none"
            )
        )
    return "\n".join(lines) + "\n"


def cmd_data_build(args) -> int:
    from ml.insider import synth

    print(json.dumps(synth.write()))
    return 0


def cmd_ml_eval(args) -> int:
    from evals.insider import ml_eval

    r = ml_eval.evaluate()
    ml_eval.write(r)
    (RESULTS / "ml-eval.md").write_text(_ml_md(r), encoding="utf-8")
    print(f"wrote docs/uc2/results/ml-eval.md; ROC-AUC IF {r['separation']['roc_auc']['isolation_forest']} "
          f"vs baseline {r['separation']['roc_auc']['statistical_baseline']}")  # fmt: skip
    return 0


def cmd_investigate(args) -> int:
    from evals.insider.agent_eval import load_golden

    from .service import build_investigator

    case = next((c for c in load_golden() if c["id"] == args.case), None)
    if case is None:
        print(f"error: unknown case {args.case}", file=sys.stderr)
        return 2
    r = build_investigator(
        args.mode, architecture=args.arch, backend=args.backend, tenant_id=args.tenant_id
    ).investigate(case)
    if args.json:
        print(json.dumps({"case": case["id"], "decision": r.decision.model_dump(), "anomaly": r.packet.anomaly.model_dump(),
                          "runs": [x.view() for x in r.runs], "totals": r.totals(), "guardrail_events": r.ctx.guardrail_events},
                         indent=1, default=str))  # fmt: skip
        return 0
    d = r.decision
    print(f"[{r.mode.upper()} · {args.arch}] {case['id']}: {d.outcome} (score {d.score}, floor {d.floor}, band "
          f"{r.packet.anomaly.anomaly_band} {r.packet.anomaly.anomaly_score})")  # fmt: skip
    for run in r.runs:
        print(f"  {run.name}: {run.stopped_reason} · {run.tool_calls} tool calls · "
              + " ".join(s["tool"] + ("" if s["ok"] else f"!{s['error']}") for s in run.steps))  # fmt: skip
    print("  reasons: " + "; ".join(d.reason_codes))
    for s in d.summary:
        print(f"  [{s['claim_type']}] {s['text']}")
    return 0


def cmd_eval(args) -> int:
    from evals.insider import agent_eval

    archs = tuple(a.strip() for a in args.arch.split(","))
    ids = [x.strip() for x in args.ids.split(",")] if args.ids else None
    r = agent_eval.run(args.mode, archs, ids, args.backend)
    stem = (
        f"agents-{args.mode}"
        + ("-" + args.backend if args.backend != "chat-completions" else "")
        + ("-subset" if ids else "")
    )
    RESULTS.mkdir(parents=True, exist_ok=True)
    (RESULTS / f"{stem}.json").write_text(
        json.dumps(r, indent=1, sort_keys=True, default=str) + "\n", "utf-8"
    )
    (RESULTS / f"{stem}.md").write_text(_agents_md(r), encoding="utf-8")
    for a, v in r["architectures"].items():
        s = v["summary"]
        print(f"{a}: acceptable {s['outcome_accuracy_acceptable']}, critical misses {s['critical_misses']}, "
              f"agents/case {s['agents_per_case']}, model calls/case {s['model_calls_per_case']}")  # fmt: skip
    print(f"wrote docs/uc2/results/{stem}.md")
    return 0


def cmd_record(args) -> int:
    """LIVE: run cases and record every model response for replay. The run's own report is the
    LIVE-VERIFIED result (`agents-live-<label>`); a later `eval --mode replay` reproduces it offline."""
    from evals.insider import agent_eval

    archs = tuple(a.strip() for a in args.arch.split(","))
    ids = [x.strip() for x in args.ids.split(",")] if args.ids else None
    r = agent_eval.run("record", archs, ids, args.backend, args.tenant_id)
    stem = f"agents-live-{args.label}"
    RESULTS.mkdir(parents=True, exist_ok=True)
    (RESULTS / f"{stem}.json").write_text(
        json.dumps(r, indent=1, sort_keys=True, default=str) + "\n", "utf-8"
    )
    (RESULTS / f"{stem}.md").write_text(_agents_md(r), encoding="utf-8")
    for a, v in r["architectures"].items():
        s = v["summary"]
        print(json.dumps({"architecture": a, "cases": s["cases"], "outcomes": s["outcomes"],
                          "acceptable": s["outcome_accuracy_acceptable"], "critical_misses": s["critical_misses"],
                          "model_calls_per_case": s["model_calls_per_case"], "tokens_per_case": s["tokens_per_case"],
                          "agent_failure_cases": s["agent_failure_cases"]}))  # fmt: skip
    print(f"wrote docs/uc2/results/{stem}.md")
    return 0


def cmd_schemas(args) -> int:
    from .service import tool_schemas

    print(json.dumps(tool_schemas(args.role), indent=2))
    return 0


def cmd_register(args) -> int:
    """LIVE: create a new version of each UC2 agent in Foundry Agent Service (additive)."""
    from .service import register_agents

    roles = tuple(r.strip() for r in args.roles.split(",")) if args.roles else None
    print(
        json.dumps(
            register_agents(args.tenant_id, roles) if roles else register_agents(args.tenant_id),
            indent=1,
        )
    )
    return 0


def cmd_obs_report(args) -> int:
    """All 36 cases replayed through the production tracer: privacy audit + telemetry summary."""
    from evals.insider.observability_report import privacy_audit, render, run_traced, summarise

    spans, cases, inv = run_traced(args.mode)
    report = {
        "mode": args.mode,
        "privacy_audit": privacy_audit(spans, cases, inv),
        "telemetry": summarise(spans),
    }
    RESULTS.mkdir(parents=True, exist_ok=True)
    (RESULTS / "observability.json").write_text(
        json.dumps(report, indent=1, sort_keys=True, default=str) + "\n", "utf-8"
    )
    (RESULTS / "observability.md").write_text(render(report), encoding="utf-8")
    print(
        f"privacy audit clean: {report['privacy_audit']['clean']}; wrote docs/uc2/results/observability.md"
    )
    return 0 if report["privacy_audit"]["clean"] else 5


def cmd_obs_live_check(args) -> int:
    """LIVE: investigations through the Foundry agents with spans exported to Application Insights.
    A fresh CANARY is planted in the flagship's security logs (a non-instruction note), so a search
    in App Insights can prove whether DataGuard's or Foundry's telemetry stores log content. UC4 and
    UC6 replay from the recorded caches; the connection string comes from the Foundry project via
    Entra sign-in and is held in memory only, never printed."""
    import secrets

    from app.agent.foundry_service import project_client, project_endpoint
    from evals.insider.agent_eval import load_golden
    from observability import azure_monitor_sink, flush_azure_monitor, load_observability_config
    from observability.config import build_tracer

    from .pipeline import InsiderInvestigator, pseudonym
    from .service import _planners, build_services

    obs_cfg, _ = load_observability_config()
    project = project_client(project_endpoint(), tenant_id=args.tenant_id)
    conn = project.telemetry.get_application_insights_connection_string()
    tracer, _ = build_tracer(obs_cfg, [azure_monitor_sink(conn)])
    del conn
    canary = f"CANARY{secrets.token_hex(4).upper()}"
    cases = {c["id"]: c for c in load_golden()}
    flag = dict(cases["I13"])
    flag["id"] = "OBS-CANARY"
    flag["overlays"] = [
        *flag["overlays"],
        {"type": "log_comment", "hour": 21, "text": f"build agent reference {canary}"},
    ]
    planners = _planners("live", "foundry-service", args.tenant_id)
    inv = InsiderInvestigator(build_services("replay"), planners, architecture="full", mode="live",
                              backend="foundry-service", tracer=tracer)  # fmt: skip
    out = []
    for case in (cases["I13"], flag, cases["I30"]):
        r = inv.investigate(case)
        out.append({"case_id": case["id"], "outcome": r.decision.outcome, "subject": pseudonym(case["user_id"]),
                    "agents": {x.name.split("-")[-1]: x.stopped_reason for x in r.runs}})  # fmt: skip
    print(json.dumps({"canary": canary, "flushed": flush_azure_monitor(), "runs": out}, indent=1))
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="dataguard-insider", description="UC2 Insider Risk")
    sub = p.add_subparsers(dest="cmd", required=True)
    d = sub.add_parser("data").add_subparsers(dest="sub", required=True)
    d.add_parser("build").set_defaults(func=cmd_data_build)
    m = sub.add_parser("ml").add_subparsers(dest="sub", required=True)
    m.add_parser("eval").set_defaults(func=cmd_ml_eval)
    i = sub.add_parser("investigate")
    i.add_argument("case")
    i.add_argument("--arch", choices=("full", "lean", "single"), default="full")
    i.add_argument("--mode", choices=("offline", "replay", "live"), default="replay")
    i.add_argument(
        "--backend", choices=("chat-completions", "foundry-service"), default="chat-completions"
    )
    i.add_argument("--tenant-id", default=None)
    i.add_argument("--json", action="store_true")
    i.set_defaults(func=cmd_investigate)
    e = sub.add_parser("eval")
    e.add_argument("--mode", choices=("offline", "replay"), default="replay")
    e.add_argument("--arch", default="single,lean,full")
    e.add_argument("--ids", default="")
    e.add_argument(
        "--backend", choices=("chat-completions", "foundry-service"), default="chat-completions"
    )
    e.set_defaults(func=cmd_eval)
    r = sub.add_parser("record")
    r.add_argument("--ids", default="")
    r.add_argument("--arch", default="single,lean,full")
    r.add_argument(
        "--backend", choices=("chat-completions", "foundry-service"), default="chat-completions"
    )
    r.add_argument("--label", default="run")
    r.add_argument("--tenant-id", default=None)
    r.set_defaults(func=cmd_record)
    o = sub.add_parser("obs").add_subparsers(dest="sub", required=True)
    orp = o.add_parser("report")
    orp.add_argument("--mode", choices=("offline", "replay"), default="replay")
    orp.set_defaults(func=cmd_obs_report)
    olc = o.add_parser("live-check")
    olc.add_argument("--tenant-id", default=None)
    olc.set_defaults(func=cmd_obs_live_check)
    a = sub.add_parser("agent").add_subparsers(dest="sub", required=True)
    s = a.add_parser("schemas")
    s.add_argument(
        "role",
        choices=(
            "orchestrator",
            "behavior",
            "investigation",
            "risk",
            "single",
            "lean_orchestrator",
        ),
    )
    s.set_defaults(func=cmd_schemas)
    rg = a.add_parser(
        "register", help="LIVE: create a new version of the four UC2 agents in Foundry"
    )
    rg.add_argument("--tenant-id", default=None)
    rg.add_argument(
        "--roles", default="", help="comma list of roles to register (default: all four)"
    )
    rg.set_defaults(func=cmd_register)
    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
